import SwiftUI
import SeismicCore
import SeismicStructures
import SeismicData

/// Report generation.
///
/// The bar set for this is that an engineer could hand it to a client without
/// embarrassment. That means stating the method as well as the result, showing
/// the assumptions, quoting the uncertainty, and being explicit about what the
/// system cannot see.
enum ReportBuilder {

    static func plainText(assessment: Assessment, building: BuildingModel) -> String {
        var lines: [String] = []

        lines.append("SEISMIC STRUCTURAL SCREENING REPORT")
        lines.append(String(repeating: "=", count: 52))
        lines.append("")
        lines.append("Building:      \(building.name)")
        if !building.address.isEmpty { lines.append("Address:       \(building.address)") }
        lines.append("Construction:  \(building.material.label), \(building.system.label)")
        lines.append("Height:        \(String(format: "%.1f m", building.height)) "
                     + "over \(building.storeyCount) storeys")
        if let year = building.yearBuilt { lines.append("Built:         \(year)") }
        lines.append("Site class:    \(building.soil.label)")
        lines.append("Assessed:      "
                     + assessment.createdAt.formatted(date: .long, time: .shortened))
        lines.append("")

        lines.append("VERDICT: \(assessment.verdict.placard)")
        lines.append(String(repeating: "-", count: 52))
        lines.append(assessment.verdict.plainMeaning)
        lines.append("")
        lines.append("Probability of structural change: "
                     + "\(Int((assessment.damageProbability * 100).rounded()))% "
                     + "(plausible range \(Int(assessment.confidenceInterval.lowerBound * 100))"
                     + "–\(Int(assessment.confidenceInterval.upperBound * 100))%)")
        lines.append("")

        lines.append("MEASUREMENTS")
        lines.append(String(repeating: "-", count: 52))
        if let before = assessment.periodBefore {
            lines.append("Baseline period:              \(String(format: "%.4f s", before))")
        }
        if let after = assessment.periodAfter {
            lines.append("Post-event period:            \(String(format: "%.4f s", after))")
        }
        if let corrected = assessment.periodAfterTemperatureCorrection {
            lines.append("Temperature-corrected:        \(String(format: "%.4f s", corrected))")
        }
        if let change = assessment.periodChangePercent {
            lines.append("Change:                       \(String(format: "%+.2f%%", change))")
        }
        if let baseline = assessment.temperatureAtBaseline,
           let measured = assessment.temperatureAtMeasurement {
            lines.append("Temperature at baseline:      \(String(format: "%.1f °C", baseline))")
            lines.append("Temperature at measurement:   \(String(format: "%.1f °C", measured))")
        }
        lines.append("")

        lines.append("EVIDENCE")
        lines.append(String(repeating: "-", count: 52))
        for (index, item) in assessment.evidence.enumerated() {
            lines.append("\(index + 1). \(item.kind.label): \(item.headline)")
            lines.append("   \(item.detail)")
            lines.append("   Source: \(item.source.label). Weight: "
                         + String(format: "%.1f", item.weight) + ".")
            lines.append("")
        }

        lines.append("ANALYSIS")
        lines.append(String(repeating: "-", count: 52))
        lines.append(assessment.narrative)
        if assessment.narrativeIsAIGenerated {
            lines.append("")
            lines.append("[This narrative was generated by a language model from the "
                         + "measurements listed above.]")
        }
        lines.append("")

        lines.append("METHOD")
        lines.append(String(repeating: "-", count: 52))
        lines.append(methodStatement)
        lines.append("")

        lines.append("LIMITATIONS")
        lines.append(String(repeating: "-", count: 52))
        lines.append(Assessment.disclaimer)
        lines.append("")

        if let hash = assessment.ledgerHash {
            lines.append("RECORD INTEGRITY")
            lines.append(String(repeating: "-", count: 52))
            lines.append("Ledger entry hash: \(hash)")
            lines.append("This assessment is recorded in a hash-chained ledger. Altering it "
                         + "after the fact breaks the chain and is detectable.")
        }

        return lines.joined(separator: "\n")
    }

    static let methodStatement = """
    The building's natural period is measured from ambient vibration using the random \
    decrement technique, and cross-checked by three independent estimators — spectral peak \
    picking with parabolic interpolation, autocorrelation, and zero-crossing rate. The \
    measurement is normalised for temperature using a regression fitted to this building's own \
    history with outlier rejection, because a building's period genuinely varies by a few per \
    cent between a cold morning and a hot afternoon.

    Ground motion is characterised by peak acceleration, velocity and displacement, Arias \
    intensity, cumulative absolute velocity and significant duration. Demand on the structure \
    is estimated by Newmark-beta integration of a lumped-mass shear model calibrated to the \
    building's empirical period, with hysteretic stiffness degradation enabled so the model \
    softens as it is damaged.

    Evidence is combined by Bayesian fusion of likelihood ratios, with the prior set by \
    fragility curves evaluated at the estimated demand. Contradictory evidence widens the \
    reported interval rather than being averaged away.
    """

    /// Rich-text-ish page model for the on-screen preview and the PDF.
    struct Page {
        var title: String
        var sections: [Section]

        struct Section: Identifiable {
            let id = UUID()
            var heading: String
            var body: String
            var rows: [(String, String)] = []
        }
    }

    static func pages(assessment: Assessment, building: BuildingModel,
                      format: ReportPreviewSheet.ReportFormat) -> [Page] {
        var pages: [Page] = []

        var summary = Page(title: "Assessment summary", sections: [])
        summary.sections.append(.init(
            heading: "Verdict",
            body: assessment.verdict.placard + ". " + assessment.verdict.plainMeaning,
            rows: [
                ("Probability of change",
                 "\(Int((assessment.damageProbability * 100).rounded()))%"),
                ("Plausible range",
                 "\(Int(assessment.confidenceInterval.lowerBound * 100))–"
                 + "\(Int(assessment.confidenceInterval.upperBound * 100))%"),
                ("Assessed",
                 assessment.createdAt.formatted(date: .abbreviated, time: .shortened)),
            ]))

        summary.sections.append(.init(
            heading: "Building",
            body: building.notes.isEmpty ? "No description recorded." : building.notes,
            rows: [
                ("Storeys", "\(building.storeyCount)"),
                ("Height", String(format: "%.1f m", building.height)),
                ("Construction", building.material.label),
                ("System", building.system.label),
                ("Site class", building.soil.label),
                ("Expected period", String(format: "%.2f s", building.empiricalPeriod)),
            ]))

        if let change = assessment.periodChangePercent {
            summary.sections.append(.init(
                heading: "Headline measurement",
                body: "The building's natural period changed by "
                    + String(format: "%+.1f%%", change)
                    + " after temperature correction. A lengthening period means reduced "
                    + "stiffness, which is what structural damage produces.",
                rows: []))
        }
        pages.append(summary)

        if format != .summary {
            var evidence = Page(title: "Evidence", sections: [])
            for item in assessment.evidence {
                evidence.sections.append(.init(
                    heading: "\(item.kind.label) — \(item.headline)",
                    body: item.detail,
                    rows: [("Source", item.source.label),
                           ("Weight", String(format: "%.1f", item.weight))]))
            }
            pages.append(evidence)

            var method = Page(title: "Method and limitations", sections: [])
            method.sections.append(.init(heading: "Method", body: methodStatement))
            method.sections.append(.init(heading: "Limitations", body: Assessment.disclaimer))
            pages.append(method)
        }

        if format == .official, let hash = assessment.ledgerHash {
            var integrity = Page(title: "Record integrity", sections: [])
            integrity.sections.append(.init(
                heading: "Tamper-evident ledger",
                body: "This assessment is recorded in a hash-chained ledger. Each entry "
                    + "incorporates the hash of the one before it, so altering any historical "
                    + "record invalidates every record after it.",
                rows: [("Entry hash", String(hash.prefix(32)) + "…")]))
            integrity.sections.append(.init(
                heading: "Signature",
                body: "Signed by: ______________________________\n\n"
                    + "Registration: ___________________________\n\n"
                    + "Date: ___________________________________"))
            pages.append(integrity)
        }

        return pages
    }
}

/// On-screen rendering of the report, which doubles as what gets printed.
struct ReportDocumentView: View {
    let assessment: Assessment
    let building: BuildingModel
    let format: ReportPreviewSheet.ReportFormat

    var body: some View {
        VStack(spacing: Theme.Metrics.spacingLoose) {
            ForEach(Array(ReportBuilder.pages(assessment: assessment, building: building,
                                              format: format).enumerated()),
                    id: \.offset) { index, page in
                VStack(alignment: .leading, spacing: Theme.Metrics.spacing) {
                    HStack {
                        Text(page.title)
                            .font(Theme.Typography.title)
                            .foregroundStyle(Theme.Palette.textPrimary)
                        Spacer()
                        Text("Page \(index + 1)")
                            .font(Theme.Typography.numericSmall)
                            .foregroundStyle(Theme.Palette.textTertiary)
                    }

                    ForEach(page.sections) { section in
                        VStack(alignment: .leading, spacing: 6) {
                            Text(section.heading)
                                .font(Theme.Typography.headline)
                                .foregroundStyle(Theme.Palette.textPrimary)
                            if !section.body.isEmpty {
                                Text(section.body)
                                    .font(Theme.Typography.callout)
                                    .foregroundStyle(Theme.Palette.textSecondary)
                                    .fixedSize(horizontal: false, vertical: true)
                            }
                            ForEach(Array(section.rows.enumerated()), id: \.offset) { _, row in
                                HStack {
                                    Text(row.0)
                                        .font(Theme.Typography.caption)
                                        .foregroundStyle(Theme.Palette.textTertiary)
                                    Spacer()
                                    Text(row.1)
                                        .font(Theme.Typography.numericSmall)
                                        .foregroundStyle(Theme.Palette.textPrimary)
                                }
                            }
                        }
                        .frame(maxWidth: .infinity, alignment: .leading)
                    }
                }
                .frame(maxWidth: .infinity, alignment: .leading)
                .instrumentPanel()
            }
        }
    }
}
